"""Initial Migration

Revision ID: 323d386ab254
Revises: 415d8645b80a
Create Date: 2019-09-26 09:31:43.238281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323d386ab254'
down_revision = '415d8645b80a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
