"""Initial Migration

Revision ID: 8482250771a3
Revises: 2b7daa39eb63
Create Date: 2019-09-29 20:01:48.310932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8482250771a3'
down_revision = '2b7daa39eb63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blog_description', table_name='blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_blog_description', 'blog', ['description'], unique=False)
    # ### end Alembic commands ###
